server:
  port: 8090

#数据源配置
spring:
  datasource:
    druid:
      name: mysql
      url: jdbc:mysql://localhost:3306/aligo
      username: root
      password: ymh96122
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 100
      initial-size: 1
      min-idle: 1
      max-wait: 60000

