spring:
  profiles:
    active: home
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/

# 手写数据库连接池用到
ext:
  datasource:
    driver: com.mysql.jdbc.Driver
    password: ymh96122
    url: jdbc:mysql://localhost:3306/aligo
    username: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.huihui.aligo.model


