spring:
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/


# 手写数据库连接池用到
ext:
  datasource:
    driver: com.mysql.jdbc.Driver
    password: ymh96122
    url: jdbc:mysql://localhost:3306/aligo
    username: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.huihui.aligo.model


# apollo配置
#app:
#  id: aligo
#apollo:
#  cluster: dev
#  bootstrap:
#    enabled: true
#    namespaces: application
#  meta: http://127.0.0.1:8080

# Dubbo框架
dubbo:
  application:
    name: member
    #协议，20880端口用于netty通信
  protocol:
    name: dubbo
    port: 20880
    #注册中心地址
  registry:
    address: zookeeper://127.0.0.1:2181
    #服务具体实现的包路径
  scan:
    base-packages: com.huihui.aligo.dubbo.impl.MemberServiceImpl




