spring:
  profiles:
    active: company

ext:
  datasource:
    driver: com.mysql.jdbc.Driver
    password: ymh96122
    url: jdbc:mysql://localhost:3306/aligo
    username: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.huihui.aligo.model

